services:
    ###
    ### Commands
    ###
    kettari_telegram.command.start:
        class: Kettari\TelegramBundle\Telegram\Command\StartCommand
        arguments:
            - '@logger'
            - '@kettari_telegram.bus'
            - '@translator'
            - '@kettari_telegram.communicator'

    kettari_telegram.command.help:
        class: Kettari\TelegramBundle\Telegram\Command\HelpCommand
        arguments:
            - '@logger'
            - '@kettari_telegram.bus'
            - '@translator'
            - '@kettari_telegram.communicator'

    kettari_telegram.command.settings:
        class: Kettari\TelegramBundle\Telegram\Command\SettingsCommand
        arguments:
            - '@logger'
            - '@kettari_telegram.bus'
            - '@translator'
            - '@kettari_telegram.communicator'
            - '@kettari_telegram.menu.settings'

    kettari_telegram.command.listroles:
        class: Kettari\TelegramBundle\Telegram\Command\ListRolesCommand
        arguments:
            - '@logger'
            - '@kettari_telegram.bus'
            - '@translator'
            - '@doctrine'
            - '@kettari_telegram.communicator'

    kettari_telegram.command.push:
        class: Kettari\TelegramBundle\Telegram\Command\PushCommand
        arguments:
            - '@logger'
            - '@kettari_telegram.bus'
            - '@translator'
            - '@doctrine'
            - '@kettari_telegram.pusher'
            - '@kettari_telegram.communicator'

    kettari_telegram.command.register:
        class: Kettari\TelegramBundle\Telegram\Command\RegisterCommand
        arguments:
            - '@logger'
            - '@kettari_telegram.bus'
            - '@translator'
            - '@doctrine'
            - '@event_dispatcher'
            - '@kettari_telegram.communicator'

    kettari_telegram.command.userman:
        class: Kettari\TelegramBundle\Telegram\Command\UserManCommand
        arguments:
            - '@logger'
            - '@kettari_telegram.bus'
            - '@translator'
            - '@doctrine'
            - '@kettari_telegram.communicator'

    kettari_telegram.command.menu:
        class: Kettari\TelegramBundle\Telegram\Command\MenuCommand
        arguments:
            - '@logger'
            - '@kettari_telegram.bus'
            - '@translator'
            - '@kettari_telegram.communicator'
            - '@kettari_telegram.menu.main'

    kettari_telegram.command.cancel:
        class: Kettari\TelegramBundle\Telegram\Command\CancelCommand
        arguments:
            - '@logger'
            - '@kettari_telegram.bus'
            - '@translator'
            - '@kettari_telegram.communicator'

    ###
    ### Menu options
    ###
    kettari_telegram.option.help:
        class: Kettari\TelegramBundle\Telegram\Command\Menu\HelpMenuOption
        arguments:
            - '@logger'
            - '@kettari_telegram.bus'
            - '@translator'
            - '@kettari_telegram.communicator'

    kettari_telegram.option.settings:
        class: Kettari\TelegramBundle\Telegram\Command\Menu\SettingsMenuOption
        arguments:
            - '@logger'
            - '@kettari_telegram.bus'
            - '@translator'
            - '@kettari_telegram.communicator'

    kettari_telegram.option.notifications:
        class: Kettari\TelegramBundle\Telegram\Command\Menu\NotificationsMenuOption
        arguments:
            - '@logger'
            - '@kettari_telegram.bus'
            - '@translator'
            - '@kettari_telegram.communicator'
            - '@doctrine'
            - '@kettari_telegram.user_hq'

    ###
    ### Menus
    ###
    kettari_telegram.menu.main:
        class: Kettari\TelegramBundle\Telegram\Command\Menu\MainMenu
        arguments:
            - '@logger'
            - '@kettari_telegram.bus'
            - '@translator'
            - '@kettari_telegram.communicator'
            - '@kettari_telegram.menu.settings'
            - '@kettari_telegram.option.help'
            - '@kettari_telegram.option.settings'

    kettari_telegram.menu.settings:
        class: Kettari\TelegramBundle\Telegram\Command\Menu\SettingsMenu
        arguments:
            - '@logger'
            - '@kettari_telegram.bus'
            - '@translator'
            - '@kettari_telegram.communicator'
            - '@kettari_telegram.option.notifications'

    ###
    ### Base services of the bot
    ###

    # Throttle control to prevent flood
    kettari_telegram.throttle:
        class: Kettari\TelegramBundle\Telegram\ThrottleControl

    # Communicator. Sends API requests to the Telegram servers
    kettari_telegram.communicator:
        class: Kettari\TelegramBundle\Telegram\Communicator
        arguments:
            - '@logger'
            - '@event_dispatcher'
            - '@kettari_telegram.throttle'

    # Pusher. Queues and sends out messages to lots of users.
    kettari_telegram.pusher:
        class: Kettari\TelegramBundle\Telegram\Pusher
        arguments:
            - '@logger'
            - '@doctrine'
            - '@kettari_telegram.communicator'

    # User's headquarters. Used to track 'current user'
    kettari_telegram.user_hq:
        class: Kettari\TelegramBundle\Telegram\UserHq
        arguments:
            - '@logger'
            - '@doctrine'

    # Command bus
    kettari_telegram.bus:
        class: Kettari\TelegramBundle\Telegram\CommandBus
        public: true
        arguments:
            - '@service_container'
            - '@logger'
            - '@doctrine'
            - '@event_dispatcher'
            - '@kettari_telegram.user_hq'
            - '@kettari_telegram.communicator'
            - '@kettari_telegram.pusher'
            - '@translator'
        calls:
            - [registerCommand, ['start', 'kettari_telegram.command.start']]
            - [registerCommand, ['settings', 'kettari_telegram.command.settings']]
            - [registerCommand, ['help', 'kettari_telegram.command.help']]
            # These standard commands commented out so if you need them, add manually
            #- [registerCommand, ['Kettari\TelegramBundle\Telegram\Command\ListRolesCommand']]
            #- [registerCommand, ['Kettari\TelegramBundle\Telegram\Command\PushCommand']]
            #- [registerCommand, ['Kettari\TelegramBundle\Telegram\Command\UserManCommand']]
            #- [registerCommand, ['Kettari\TelegramBundle\Telegram\Command\RegisterCommand']]
            #- [registerCommand, ['menu', 'kettari_telegram.command.menu']]

    ### Default subscribers
    # Audit subscriber
    kettari_telegram.subscriber.audit:
        class: Kettari\TelegramBundle\Telegram\Subscriber\AuditSubscriber
        arguments:
            - '@logger'
            - '@doctrine'

    # Resolves current user. Makes sure we have user entity after this subscriber
    kettari_telegram.subscriber.user_identity:
        class: Kettari\TelegramBundle\Telegram\Subscriber\UserIdentitySubscriber
        arguments: 
            - '@logger'
            - '@kettari_telegram.communicator'
            - '@translator'
            - '@kettari_telegram.user_hq'
        
    # Hooker subscriber
    kettari_telegram.subscriber.hooker:
        class: Kettari\TelegramBundle\Telegram\Subscriber\HookerSubscriber
        arguments: 
            - '@logger'
            - '@kettari_telegram.bus'
            - '@kettari_telegram.communicator'
            - '@translator'

    # Update subscriber
    kettari_telegram.subscriber.update:
        class: Kettari\TelegramBundle\Telegram\Subscriber\UpdateSubscriber
        arguments: 
            - '@logger'
            - '@event_dispatcher'

    # Resolves current chat. Makes sure we have chat entity after this subscriber
    kettari_telegram.subscriber.chat_identity:
        class: Kettari\TelegramBundle\Telegram\Subscriber\ChatIdentitySubscriber
        arguments: 
            - '@logger'
            - '@doctrine'

    # Message subscriber
    kettari_telegram.subscriber.message:
        class: Kettari\TelegramBundle\Telegram\Subscriber\MessageSubscriber
        arguments: 
            - '@logger'
            - '@event_dispatcher'
            - '@kettari_telegram.communicator'

    # Text subscriber
    kettari_telegram.subscriber.text:
        class: Kettari\TelegramBundle\Telegram\Subscriber\TextSubscriber
        arguments: 
            - '@logger'
            - '@event_dispatcher'

    # Command subscriber
    kettari_telegram.subscriber.command:
        class: Kettari\TelegramBundle\Telegram\Subscriber\CommandSubscriber
        arguments: 
            - '@logger'
            - '@event_dispatcher'
            - '@kettari_telegram.bus'
            - '@kettari_telegram.communicator'
            - '@translator'
        
    # Keeps track of users join and part from chats
    kettari_telegram.subscriber.chat_member:
        class: Kettari\TelegramBundle\Telegram\Subscriber\ChatMemberSubscriber
        arguments: 
            - '@logger'
            - '@doctrine'
            - '@event_dispatcher'
            - '@kettari_telegram.user_hq'

    # Handles new chats creation
    kettari_telegram.subscriber.group:
        class: Kettari\TelegramBundle\Telegram\Subscriber\GroupSubscriber
        arguments: 
            - '@logger'
            - '@doctrine'

    # Handles chat migration (group → supergroup)
    kettari_telegram.subscriber.chat_migration:
        class: Kettari\TelegramBundle\Telegram\Subscriber\ChatMigrationSubscriber
        arguments: 
            - '@logger'
            - '@doctrine'

    # User registration subscriber, command /register
    kettari_telegram.subscriber.user_registration:
        class: Kettari\TelegramBundle\Telegram\Subscriber\UserRegistrationSubscriber
        arguments: 
            - '@logger'
            - '@kettari_telegram.pusher'
            
    # Answers unhandled requests with default menu
    kettari_telegram.subscriber.menu:
        class: Kettari\TelegramBundle\Telegram\Subscriber\MenuSubscriber
        arguments: 
            - '@logger'
            - '@kettari_telegram.bus'

    # Bot service
    kettari_telegram.bot:
        class: Kettari\TelegramBundle\Telegram\Bot
        public: true
        arguments:
            - '@logger'
            - '@event_dispatcher'
            - '@kettari_telegram.bus'
            - '@kettari_telegram.communicator'
        calls:
            - [addSubscriber, ['@kettari_telegram.subscriber.audit']]
            - [addSubscriber, ['@kettari_telegram.subscriber.user_identity']]
            - [addSubscriber, ['@kettari_telegram.subscriber.hooker']]
            - [addSubscriber, ['@kettari_telegram.subscriber.update']]
            - [addSubscriber, ['@kettari_telegram.subscriber.chat_identity']]
            - [addSubscriber, ['@kettari_telegram.subscriber.message']]
            - [addSubscriber, ['@kettari_telegram.subscriber.text']]
            - [addSubscriber, ['@kettari_telegram.subscriber.command']]
            - [addSubscriber, ['@kettari_telegram.subscriber.chat_member']]
            - [addSubscriber, ['@kettari_telegram.subscriber.group']]
            - [addSubscriber, ['@kettari_telegram.subscriber.chat_migration']]
            - [addSubscriber, ['@kettari_telegram.subscriber.user_registration']]
            - [addSubscriber, ['@kettari_telegram.subscriber.menu']]

    # Shortcuts
    telegram:
        alias: kettari_telegram.bot
        public: true

    command_bus:
        alias: kettari_telegram.bus
        public: true