services:
    kettari.telegram.bot:
        class: Kaula\TelegramBundle\Telegram\Bot
        arguments: ['@service_container']

    kettari.telegram.bus:
        class: Kaula\TelegramBundle\Telegram\CommandBus
        arguments: ['@kettari.telegram.bot']

    telegram_bot:
        alias: kettari.telegram.bot
        arguments: ['@service_container']

    command_bus:
        alias: kettari.telegram.bus
        arguments: ['@kettari.telegram.bot']
