services:
    kettari_telegram.bot:
        class: Kaula\TelegramBundle\Telegram\Bot
        arguments: ['@service_container']

    kettari_telegram.bus:
        class: Kaula\TelegramBundle\Telegram\CommandBus
        arguments: ['@kettari_telegram.bot']

    telegram_bot:
        alias: kettari_telegram.bot
        arguments: ['@service_container']

    command_bus:
        alias: kettari_telegram.bus
        arguments: ['@kettari_telegram.bot']
