services:
    kaula_telegram.bot:
        class: Kaula\TelegramBundle\Telegram\Bot
        arguments: ['@service_container']

    kaula_telegram.bus:
        class: Kaula\TelegramBundle\Telegram\CommandBus
        arguments: ['@kaula_telegram.bot']

    telegram_bot:
        alias: kaula_telegram.bot
        arguments: ['@service_container']

    command_bus:
        alias: kaula_telegram.bus
        arguments: ['@kaula_telegram.bot']
